[package]
name = "behaviortree"
version = "0.1.1"
edition = "2021"

[dependencies]
serde = { workspace = true }

behaviortree_common = { path = "../behaviortree_common" }

[dev-dependencies]
serde_json = "1.0"
