[package]
name = "async_behaviortree"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }

behaviortree_common = { path = "../behaviortree_common" }

async-trait = "0.1.80"

[dev-dependencies]
ticked_async_executor = "0.2"

tokio-stream = { version = "0.1.15", features = ["full"] }
