[package]
name = "async_behaviortree"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }

behaviortree_common = { path = "../behaviortree_common" }

async-trait = "0.1.80"

[dev-dependencies]
ticked_async_executor = { git = "https://github.com/coder137/ticked-async-executor", rev = "a792d18fa778613138b91b493e95768d448613a1" }

tokio-stream = { version = "0.1.15", features = ["full"] }
