[package]
name = "async_behaviortree"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }

behaviortree_common = { path = "../behaviortree_common" }

async-trait = "0.1.80"

[dev-dependencies]
ticked_async_executor = { git = "https://github.com/coder137/ticked-async-executor", rev = "45c76da3730e0f77f08c9f6af86f00832c89fe1e" }

tokio-stream = { version = "0.1.15", features = ["full"] }
