[package]
name = "async_behaviortree"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }

behaviortree_common = { path = "../behaviortree_common" }

async-trait = "0.1.80"
async-std = "1.12.0"

tokio = { version = "1.38.0", default-features = false, features = [
    "macros",
    "sync",
] }

[dev-dependencies]
ticked_async_executor = { git = "https://github.com/coder137/ticked-async-executor", rev = "e7179511f1c6c834fbe81ab16b31d5dbf4e50218" }
