name: Rust CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: behaviortree package
        working-directory: ${{github.workspace}}/behaviortree
        run: |
          cargo clippy
          cargo test
          cargo build
          cargo run --example simple_immediate_sync
